USE EShop

--This is a comment
--Get all products
Select * from Product
--Get all products that have category id=10
Select * from Product 
Where CategoryId=10 

--Get total cost of products listed woth category id=10
Select Sum(Cost) from Product 
Where CategoryId=10

--Get product name,cost from product table
Select name, Cost from Product

--save above as view
CREATE VIEW vw_Product AS 
Select name, Cost from Product

--see the view result
select * from vw_Product

--Get all products that starts with 'K'
Select * from Product
Where Name Like '%K%'

--get 2nd character as k
Select * from Product
Where name like '_k%'

--get all products whose cost is not equal to 900
Select * from Product
Where Cost <> 900


Select * from Product
Where Name like 'K%a' --starts with K ends with a

-- Select all products with names as 'T-Shirt' ,'IPhone,'Kurta'
Select * from Product
Where Name='T-Shirt' OR Name='IPhone' OR Name='Kurta'

--better technique
Select * from Product
Where Name in ('T-Shirt','IPhone','Kurta')

--Get all products having category Id matching a category in productCategory table
Select * from Product
Where CategoryId IN (Select Id from ProductCategory)

--get customer name and order Id for all customers
Select [Name], [OrderId] from Customer,Orders
Where CustomerId = Orders.CustomerId 

--get total revenue generated by Parth, name from customer, total cost from product,orders table contains Customer purchases
Select Sum(Cost)
From Orders, Customer,Product
Where Orders.CustomerId = CustomerId
AND Orders.ProductId=ProductId
AND Customer.Name='Parth'


